### ISSUE TITLE
(Windows 10/11) An error occurred while trying to add the installer

### ISSUE THREAD

**Issue by nmihayl** [JoshuaVandaele/SuperISOUpdater#10]
This bug occurs when downloads for Windows 10 and Windows 11 are enabled in the config.toml file. The error provides a traceback:

`Traceback (most recent call last):
  File "/home/nick/.local/lib/python3.12/site-packages/sisou.py", line 112, in run_updaters
    updaters.append(updater_class(install_path, **param))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nick/.local/lib/python3.12/site-packages/modules/updaters/Windows11.py", line 102, in __init__
    raise ConnectionError("Failed to fetch the main content from the webpage")
ConnectionError: Failed to fetch the main content from the webpage`

It seems that SISOU is unable to connect in order to initiate the ISO download (perhaps a filename mismatch?). This also occurs with Windows 10, complete with the same traceback.

**Information (please complete the following information):**
 - Installer: Windows10 and Windows11
 - Python 3.12.7
 - Fedora Linux 40

**Additional context**
In the event that this happens to be a regional thing, I am in Germany if this helps somewhat and I have not tested if using a VPN would make a difference. Though I am willing to guess that this is a filename mismatch which SISOU cannot find on the Microsoft domain when trying to download the file.

**Comment by JoshuaVandaele** [comment]
Thanks for the detailed bug report! It turned out to be a change to Microsoft's website which made parsing fail, you should be able to successfully download Windows now using the latest version

**Comment by nmihayl** [comment]
Thanks a ton for the quick fix, I'm finally getting around to testing it and want to report that Windows 10 22H2 English International downloads fine, but Windows 11 English International throws the following:

```
2024-11-04 08:46:28,834 - ERROR - [Windows11 {'lang': 'English International'}] An error occurred while trying to add the installer. See traceback below.
Traceback (most recent call last):
  File "/home/deck/.local/lib/python3.12/site-packages/sisou.py", line 112, in run_updaters
    updaters.append(updater_class(install_path, **param))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.12/site-packages/modules/updaters/Windows11.py", line 102, in __init__
    raise ConnectionError("Failed to fetch the main content from the webpage")
ConnectionError: Failed to fetch the main content from the webpage
```

**Comment by JoshuaVandaele** [comment]
I had only implemented the fix for Windows 10 - Oops! Windows 11 should work too now :)
