### ISSUE TITLE
Cannot install with python3

### ISSUE THREAD

**Issue by lostallmymoney** [JoshuaVandaele/SuperISOUpdater#6]
cc@cc-1-0:~/Desktop/SuperISOUpdater-1.1.3$ sh
$ python3 -m pip install sisou
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
$ exit
cc@cc-1-0:~/Desktop/SuperISOUpdater-1.1.3$ python3 -m pip install .
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
cc@cc-1-0:~/Desktop/SuperISOUpdater-1.1.3$ 

What worked was using pipx.

**Comment by JoshuaVandaele** [comment]
This is due to your distribution trying to follow PEP 668 (Trying to protect you against mixing apt packages and pip packages), in which case you may need to use pipx or venv's, as indicated in the error message. This is normal, but thanks for the report!
