### ISSUE TITLE
No hash verification

### ISSUE THREAD

**Issue by lostallmymoney** [JoshuaVandaele/SuperISOUpdater#7]
**Describe the bug**
No verification of the ISO files before moving onto the next step. (moving them into folders)

**To Reproduce**

Update any iso.
Spam close the process (ctrl+C or ctrl+Z).
Restart the process.
Constate that a 360kb file is now my debian ISO and there is no update.

**Expected behavior**

Completion verification at least. But SHA256 verification would be the right thing to do. Perhaps with a setting to toggle.

Some downloads will eventually be faulty, leading to the moment where a user cannot get their distro to run for unknown reasons. Before they redownload the right ISO they will fiddle a bit, leading to frustrations.

**Comment by lostallmymoney** [comment]
I noticed there seems to be some support for verification, but it is not totally implemented. Verifying the download has finished/size would do the trick for some. :)

**Comment by JoshuaVandaele** [comment]
All ISOs are verified, to the highest form possible (SHA512, SHA256, SHA1, MD5) it all depends on what is provided by the download source. However the verification occurs only after the download is over! Therefore, if the program terminates early, the file would not have yet have had time to be checked and deleted if appropriate.

**Comment by JoshuaVandaele** [comment]
Closed in 56275697e2b81156527dd8fdc15a4dcd10117b2d
